name: Send WhatsApp Message Workflow

on:
  workflow_dispatch:
    inputs:
      phone_number:
        description: 'Kise bhejna hai? (Ex: 9198XXXXXXXX)'
        required: true
        default: '91'
      message_text:
        description: 'Kya message bhejna hai?'
        required: true
        default: 'Hello from GitHub!'

jobs:
  whatsapp-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node index.js
        env:
          WHATSAPP_TOKEN: ${{ secrets.WHATSAPP_TOKEN }}
          PHONE_NUMBER_ID: ${{ secrets.PHONE_NUMBER_ID }}
          RECIPIENT_NUMBER: ${{ github.event.inputs.phone_number }}
          MESSAGE_BODY: ${{ github.event.inputs.message_text }}
